{% set name = "apoc-backend" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/apoc/apoc-{{ version }}.tar.gz
  sha256: 9821da2f36732c4945a96cf61bb8411cad3fc9dd7656106e5bd3de7342505b25

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy >=1.21
    - pyclesperanto-prototype >=0.19.0
    - python >=3.6
    - scikit-learn >=0.24.2
    - pandas

test:
  imports:
    - apoc
  commands:
    - pip list
    - pip check
  requires:
    - oclgrind
    - pip

about:
  home: https://github.com/haesleinhuepf/apoc
  summary: Accelerated Pixel and Object Classifiers based on OpenCL
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - haesleinhuepf
