{% set name = "apoc-backend" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/a/apoc/apoc-{{ version }}.tar.gz
  sha256: c6e5264f2ac0420e5f8e2b23ad16927126d75280bb12f0341480ef9853973263

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - numpy >=1.21
    - pyclesperanto-prototype >=0.21.1
    - python >={{ python_min }}
    - scikit-learn >=0.24.2
    - pandas

test:
  imports:
    - apoc
  commands:
    - pip list
    - pip check
  requires:
    - oclgrind
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/haesleinhuepf/apoc
  summary: Accelerated Pixel and Object Classifiers based on OpenCL
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - haesleinhuepf
